// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_WBc65MpxWSAk91Z6ZdQClUzl3X_tC4',
    appId: '1:43120035722:web:49715c3615ac0625d1aa73',
    messagingSenderId: '43120035722',
    projectId: 'ask-crew',
    authDomain: 'ask-crew.firebaseapp.com',
    storageBucket: 'ask-crew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXhWehGbaQNTibQDM7Lw0wR9tpGxW1aA',
    appId: '1:43120035722:android:4c6431f2c7b1ed6cd1aa73',
    messagingSenderId: '43120035722',
    projectId: 'ask-crew',
    storageBucket: 'ask-crew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSm3kKOTRFZ7eKYb8J9Z0Uu8DuPd3gTY',
    appId: '1:43120035722:ios:0bb621a9d638a54ed1aa73',
    messagingSenderId: '43120035722',
    projectId: 'ask-crew',
    storageBucket: 'ask-crew.firebasestorage.app',
    iosBundleId: 'com.askcrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSm3kKOTRFZ7eKYb8J9Z0Uu8DuPd3gTY',
    appId: '1:43120035722:ios:0bb621a9d638a54ed1aa73',
    messagingSenderId: '43120035722',
    projectId: 'ask-crew',
    storageBucket: 'ask-crew.firebasestorage.app',
    iosBundleId: 'com.askcrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE_WBc65MpxWSAk91Z6ZdQClUzl3X_tC4',
    appId: '1:43120035722:web:a77c5bbda9d7a831d1aa73',
    messagingSenderId: '43120035722',
    projectId: 'ask-crew',
    authDomain: 'ask-crew.firebaseapp.com',
    storageBucket: 'ask-crew.firebasestorage.app',
  );
}
